name: Build and Release Windows EXE

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore AdvancedAntivirus/AdvancedAntivirus.csproj

    - name: Build
      run: dotnet build AdvancedAntivirus/AdvancedAntivirus.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish AdvancedAntivirus/AdvancedAntivirus.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true -o ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AdvancedAntivirus-Windows-EXE
        path: ./publish/AdvancedAntivirus.exe
